apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-html
  namespace: apache-ssl
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Apache Personnalisé</title>
        <style>
            body { font-family: Arial; text-align: center; margin-top: 50px; }
            h1 { color: #2c3e50; }
            p { color: #34495e; }
        </style>
    </head>
    <body>
        <h1>Bienvenue sur mon Apache personnalisé !</h1>
        <p>Ceci n’est pas la page par défaut.</p>
    </body>
    </html>
