apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2-deployment
  namespace: apache-ssl
  labels:
    app: apache2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
        - name: apache2
          image: ghcr.io/servercontainers/apache2-ssl-secure:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/local/apache2/htdocs/
      volumes:
        - name: html-volume
          configMap:
            name: apache-html
            items:
              - key: index.html
                path: index.html
