apiVersion: v1
kind: Service
metadata:
  name: apache2-service
  namespace: apache-ssl
spec:
  selector:
    app: apache2
  ports:
    - protocol: TCP
      port: 80          # Port interne du cluster
      targetPort: 80    # Port du pod
      nodePort: 30082   # Port expos√© sur le master
  type: NodePort
