apiVersion: v1
kind: Service
metadata:
  name: tiny-httpd-service
  namespace: tiny-httpd
spec:
  selector:
    app: tiny-httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
