apiVersion: v1
kind: Service
metadata:
  name: apache2-service
  namespace: apache-ssl
spec:
  selector:
    app: apache2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
