apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-test-prod
resources:
  - ../../base
  - namespace.yaml
namePrefix: prod-
patchesStrategicMerge:
  - patch-configmap.yaml
  - service-patch.yaml