apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  # - namespace.yaml  <--- RETIRÃ‰: On utilise le champ 'namespace:' ci-dessous.

namePrefix: prod-

# AJOUT DE CETTE LIGNE
namespace: nginx-test-prod # <--- CORRECTION: Indique le Namespace pour TOUTES les ressources.

patchesStrategicMerge:
  - patch-configmap.yaml
  - service-patch.yaml