apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml  # <--- CORRECTION: La définition de Namespace est une ressource, pas un patch.

namePrefix: prod- 

patchesStrategicMerge:
  - patch-configmap.yaml
  - service-patch.yaml
  # Le fichier namespace.yaml a été retiré de cette section.