apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-test-dev
resources:
  - ../../base
  - namespace.yaml
namePrefix: dev-
patchesStrategicMerge:
  - patch-configmap.yaml
  - service-patch.yaml