name: Trivy Scan - YAML Projet1-Azure

on:
  workflow_dispatch:

jobs:
  scan_yaml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Lancer le scan Trivy sur tous les fichiers YAML
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'        # <- remplacer iac par config
        input: './DEVSECOPS/'      # dossier contenant apache et nginx
        format: 'table'
        severity: 'CRITICAL,HIGH'
        exit-code: '0'
        ignore-unfixed: 'false'
        output: 'trivy-report.txt'

    - name: Upload du rapport Trivy en tant qu'artefact
      uses: actions/upload-artifact@v4
      with:
        name: trivy-yaml-report
        path: trivy-report.txt
