name: Trivy Scan - Fichiers YAML

on:
  workflow_dispatch:

jobs:
  scan_yaml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Lancer le scan Trivy sur tous les fichiers YAML
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'              # 'fs' = filesystem scan (scan de fichiers)
        format: 'table'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'
        # On cible tous les fichiers YAML
        input: './'                  # le r√©pertoire racine du repo
        include: '**/*.yml,**/*.yaml'
        output: 'trivy-report-yaml.txt'

    - name: Upload du rapport Trivy en tant qu'artefact
      uses: actions/upload-artifact@v4
      with:
        name: trivy-yaml-report
        path: trivy-report-yaml.txt
