name: Trivy Scan - Tous les YAML

on:
  workflow_dispatch:

jobs:
  scan_yaml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Lancer le scan Trivy sur tous les fichiers YAML
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'       # scan de fichiers
        input: './'           # racine du repo
        format: 'table'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'
        ignore-unfixed: 'false'
        output: 'trivy-report.txt'  # <- crÃ©ation du fichier de sortie

    - name: Upload du rapport Trivy en tant qu'artefact
      uses: actions/upload-artifact@v4
      with:
        name: trivy-yaml-report
        path: trivy-report.txt
